### ISSUE TITLE
Windows Configuration Not Working

### ISSUE THREAD

**Issue by p3lewis** [SetBased/php-stratum#1]
Firstly, I really am hoping that I can get this to work on my windows machine, because I have been looking for something like this solution for a long time. Really good work guys!

My development environment is on a Windows machine that connects to a WAMP backend. I eventually want to push the php code to a LINUX web server. I want to leverage stored procedures in my database from the PHP application classes.

Here is my issue, my configuration file (attached) is giving me errors (also attached). I have also created a screenshot of the file system folders after using COMPOSER to get the files. Also attached is the composer file. Can you please take a look and advise what I am doing wrong please or if infact this solution can work on WINDOWS.

Please help!

![stratum cfg](https://cloud.githubusercontent.com/assets/16584127/12158184/95b287e4-b4a5-11e5-84e0-d4e42929595b.png)
![run_config_errors](https://cloud.githubusercontent.com/assets/16584127/12158207/d452739c-b4a5-11e5-9573-607542c3de1c.png)
![file_system_structure](https://cloud.githubusercontent.com/assets/16584127/12158250/54100e64-b4a6-11e5-90d3-54366d03b87a.png)
![composer json](https://cloud.githubusercontent.com/assets/16584127/12158265/7418d3d0-b4a6-11e5-8957-26defbf264a4.png)

**Comment by p3lewis** [comment]
Forgot to attach the errors...
See attached...
![run_config_errors](https://cloud.githubusercontent.com/assets/16584127/12158303/d62aa738-b4a6-11e5-83f6-3f4acbd21fd3.png)

**Comment by SetBased** [comment]
Hello p3lewis,

Thanks for your compliments.

I see you followed the configuration as shown in the [samples](https://github.com/SetBased/php-stratum-samples). Unfortunately, the samples were lagging behind some changes in PhpStratum that had impact on the configuration files. I have updated the samples and they are working fine under Linux. Please, let me know if you have any problem running the samples under Windows.

I think your  configuration file should look like:
```text
[database]
host_name     = localhost
user_name     = my_user_root
password      = my_password
database_name = my_mysql_db

[wrapper]
parent_class  = \SetBased\Stratum\MySql\StaticDataLayer
mangler_class = \SetBased\Stratum\NameMangler\SetBasedNameMangler
wrapper_class = DataLayer
wrapper_file  = src/DataLayer.php
metadata      = etc/routines.json

[loader]
source_directory = lib/psql
extension        = .psql
constant_class   = YourNameSpace\C
sql_mode         = STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
character_set    = utf8
collate          = utf8_general_ci

[constants]
columns = etc/columns.txt
class   = YourNameSpace\C
prefix  = LEN_
```
In the configuration file above I assumed that:
* Your PHP sources are under directory src
* Your configuration files are under directory etc
* Your stored routines are under directory lib/psql

You can changes those directories according your taste and coding standards.

Make sure you have a class for the generated constants:
```php
<?php
namespace YourNameSpace;

/**
 * Class for manually and automatically generated constants.
 */
class C
{
  /**
   * @setbased.stratum.constants
   *
   * Below this doc block constants will be inserted by PhpStratum.
   */

}
```

**Comment by SetBased** [comment]
Hello p3lewis,

If you any questions just let me know. 

BTW We are working on the manual of PhpStratum.
